library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_new_student', views.add_new_student, name='new_student'),
    path('add_new_book', views.add_new_book, name='new_book'),
    path('add_book_issue', views.add_book_issue, name='book_issue'),
    path('add_new_book_instance', views.add_new_book_instance, name='add_new_book_instance'),
    path('show_students', views.view_students, name='show_student_record'),
    path('view_books', views.view_books, name='show_book_record'),
    path('view_books_issued', views.view_bissue, name='show_issue_record'),
    path('edit/student/<str:roll>',views.edit_student_data,name="Edit Student data"),
    path('edit/book/<uuid:id>',views.edit_book_data,name="Edit Student data"),
    path('delete/student/<str:roll>',views.delete_student,name="Delete Student data"),
    path('delete/book/<str:id>',views.delete_book,name="Delete book data"),
    path('return_book/<int:id>',views.return_issued_book,name="return_issued_book"),
    path('edit_issued/<int:id>',views.edit_issued,name="edit_issued"),

]

library/models.py
from django.db import models
from datetime import datetime,timedelta
import uuid

class Students(models.Model):
    mat_no = models.CharField(max_length=100,unique=True)
    fullname = models.CharField(max_length=100 ,help_text="surname first")
    study_program = models.CharField(max_length=100)
    student_dept = models.CharField(max_length=100)
    student_faculty = models.CharField(max_length=100)
    email=models.EmailField(max_length=100,help_text="student e-mail")
    def __str__(self):
        return self.fullname
        
class Staff(models.Model):
    staff_id = models.CharField(max_length=100,unique=True)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    Email=models.EmailField(max_length=100,help_text="staff e-mail")
    def __str__(self):
        return self.fullname

class Book(models.Model):
    book_title = models.CharField(max_length=200)
    book_author = models.CharField(max_length=100)
    book_pages = models.PositiveIntegerField()
    book_category = models.CharField(max_length=100, help_text="category the book falls into, for instance fiction, romance")
    book_description=models.TextField(max_length=200, help_text="Short description about the book",null=True,blank=True)
    def __str__(self):
        return self.book_title

class BookInstance(models.Model):
    id=models.AutoField(primary_key=True,help_text="Book unique id across the Library")
    book=models.ForeignKey('Book', on_delete=models.CASCADE,null=True)
    book_number=models.PositiveIntegerField(null=True,help_text="Book number for books of the save kind")
    Is_borrowed = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.id} {self.book}"

def get_returndate():
    return datetime.today() + timedelta(days=8)

class Book_Issue(models.Model):
    student = models.ForeignKey('Students', on_delete=models.CASCADE)
    book_instance = models.ForeignKey('BookInstance', on_delete=models.CASCADE)
    issue_date = models.DateTimeField(auto_now=True,help_text="Date the book is issued")
    due_date = models.DateTimeField(default=get_returndate(),help_text="Date the book is due to")
    date_returned=models.DateField(null=True, blank=True,help_text="Date the book is returned")
    remarks_on_issue = models.CharField(max_length=100, default="Book in good condition", help_text="Book remarks/condition during issue")
    remarks_on_return = models.CharField(max_length=100, default="Book in good condition", help_text="Book remarks/condition during return")

    def __str__(self):
        return self.student.fullname + " borrowed " + self.book.book_title

library/forms.py
from django import forms
from .models import Students, Book, Book_Issue,BookInstance

class StudentsForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        
class Book_instanceForm(forms.ModelForm):
    class Meta:
        model=BookInstance
        fields = ['book','book_number']

class Book_IssueForm(forms.ModelForm):
    class Meta:
        model=Book_Issue
        exclude = ['issue_date', 'due_date','remarks_on_return','date_returned']

library/views.py
from django.shortcuts import render, redirect,HttpResponse
from .forms import StudentsForm, BookForm, Book_IssueForm,Book_instanceForm
from .models import Students, Book, Book_Issue,BookInstance


def index(request):
    return(render(request, 'index.html'))


def add_new_student(request):
    if request.method=="POST":
        form = StudentsForm((request.POST))
        if form.is_valid():
            form.save()
            return redirect('/show_students')
    else:
        form = StudentsForm
    return (render(request, 'add_new_student.html', {'form':form}))


def add_new_book(request):
    if request.method=="POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form=form.save()
            book_instance=BookInstance(book=form)
            book_instance.save()
            return redirect('/view_books')
    else:
        form = BookForm
        form_instance=Book_instanceForm
        return (render(request, 'add_new_book.html', {'form':form,"form_instance":form_instance}))

def add_new_book_instance(request):
    form=Book_instanceForm(request.POST)
    if form.is_valid():
        form.save()
    return redirect('/view_books')


def add_book_issue(request):
    if request.method=="POST":
        form = Book_IssueForm(request.POST)
        if form.is_valid():
            # save data
            unsaved_form=form.save(commit=False)
            book_to_save=BookInstance.objects.get(id=unsaved_form.book_instance.id)
            book_to_save.Is_borrowed=True
            book_to_save.save()
            form.save()
            form.save_m2m()
        return redirect('/view_books_issued')
    else:
        context={'form':Book_IssueForm,"book":BookInstance.objects.filter(Is_borrowed=False)}
        return render(request, 'add_book_issue.html',context=context)

def view_students(request):
    students = Students.objects.order_by('-id')
    return render(request,'view_students.html', {'students': students})

def view_books(request):
    books=BookInstance.objects.order_by('id')
    return render(request,'view_books.html', {'books': books})

def view_bissue(request):
    issue = Book_Issue.objects.order_by('-id')
    return render(request,'issue_records.html', {'issue': issue})


def edit_student_data(request,roll):
    try:
        if request.method == "POST":
            std=Students.objects.get(id=request.session['id'])    
            form = StudentsForm((request.POST),instance=std)
            if form.is_valid():
                form.save()
            del request.session['id']
            return redirect("/show_students")
        else:
            student_to_edit=Students.objects.get(roll_number=roll)
            student=StudentsForm(instance=student_to_edit)
            request.session["id"]=student_to_edit.id
            return render(request,'edit_student_data.html',{'student':student})
    except Exception as error:
        print(f"{error} occured at edit_student_data view")

def edit_book_data(request,id):
    return HttpResponse(f"<label>A book with ID: {id} could not be edited...</label><h2>The feature is comming soon</h2>")

def delete_student(request,roll):
    obj=Students.objects.get(id=roll)
    obj.delete()
    return redirect('/show_students')

def delete_book(request,id):
    return HttpResponse(f"<h2>Delete Book</h2><label>Book with ID: {id} could not be deleted..</label><h2>The feature is comming soon</h2>")

def return_issued_book(request,id):   
    obj=Book_Issue.objects.get(id=id)
    obj.delete()
    return HttpResponse(f"<h2>Return Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be returned..</label><h2>The feature is comming soon</h2>")

def edit_issued(request, id):
    obj=Book_Issue.objects.get(id=id)
    return HttpResponse(f"<h2>Edit Issued Book</h2><label>Book <i>{obj.book_instance.book.book_title}</i> issued to <i>{obj.student.fullname}</i> could not be edited..</label><h2>The feature is comming soon</h2>")

library/templates/add_book_issue.html
<title>Add Book Issue</title>
{% extends 'base.html' %}

<body>
{% block content %}

<div class="form-div" >
<form method="POST" action="add_book_issue" class="form-inline">
    {% csrf_token %}
    <label>Student Details</label>
    <br>
    <div id="student_selection">
        <div>{{form.student}}</div>
            <div><input type="text" placeholder="Quick Student Search" id="quick" onkeyup="Quick_search()">
                <div id="quick_student_search_view"></div>
            </div>
    </div>

    <br>
    <hr>
    <div class="book_selection">
        <label>Book Details</label>
        <br>
        <select name="book_instance" required id="id_book_instance">
            <option value="" selected>select</option>
            {%for i in book%}
                <option class="selection" value="{{i.id}}">{{i.book.book_title}} (: {{i.id}})</option>
            {%endfor%}
        </select>
        <div>
            <input type="text" placeholder="Quick Book Search" id="quick_book_search" onkeyup="Quick_book_search()">
            <div class="together" id="quick_book_search_view"></div>
        </div>
    </div>
<hr>
    <label style="visibility: hidden;">Remarks</label><br> <div  style="visibility: hidden;"> {{form.remarks_on_issue}}</div>
    <br> 
    <button type="submit" class="btn btn-success" >Issue Book</button>

</form>


<script type="text/javascript">
    function Quick_search(){
        var input, items,view;
        input = document.getElementById('quick').value.toLowerCase();
        items = document.getElementById('id_student');
        view=document.getElementById("quick_student_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if(input !== "" && (item.toLowerCase().indexOf(input)>-1 )){
                    var list_added = document.createElement("label");
                    list_added.appendChild(document.createTextNode(item));
                    list_added.onclick =function(){
                        items.children[get_clicked_value(this.innerHTML)].setAttribute("selected",true);
                        view.style.display="none";
                        // uncomment below line to hide the search input after selection is made
                        document.getElementById('quick').style.display="none";
                    };
                    view.appendChild(list_added);
                    view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function get_clicked_value(clicked){
        var items = document.getElementById('id_student');
        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i];
                if (item.innerHTML == clicked ) {
                    return item.getAttribute("value");
                }
        }
    }

    // Quick book search
    function Quick_book_search(){
        var input, items,view;
        input = document.getElementById('quick_book_search');
        items = document.getElementById('id_book_instance');
        view=document.getElementById("quick_book_search_view");
        view.replaceChildren("");

        for(i=1;i<items.children.length.valueOf();i++){
            var item=items.children[i].innerHTML;
            if((input.value.toLowerCase() !== "") && (item.toLowerCase().indexOf(input.value.toLowerCase())>-1 ) ){
                var list_added = document.createElement("label");
                list_added.appendChild(document.createTextNode(item));
                list_added.onclick =function(){
                    select_clicked_book(this.innerHTML);
                    view.style.display="none";
                    // comment below line to unhide the search input after selection is made
                    input.style.display="none"; input.value="";
                };
                view.appendChild(list_added);
                view.style.display="block";
            }
            else{
                view.style.display="none";
            }
        }
    }
    function select_clicked_book(clicked){
        var books = document.getElementById('id_book_instance');   
        for(i=1;i<books.children.length.valueOf();i++){
            var item=books.children[i];
                if (item.innerHTML == clicked ) {
                    item.setAttribute("selected",true);
                }
        }
    }
</script>
</div>
{% endblock %}
</body>
</html>

library/templates/add_new_book.html
<title>Add New Book</title>
{% extends 'base.html' %}

<body>
{% block content %}

    <!-- <div class="tablinks">
        <button onclick="opentab(name)" class="link" name="new_book">New Book</button>
        <button onclick="opentab(name)" class="link" name="new_book_instance">New Book Instance</button>
    </div> -->

    <!-- <div id="new_book" class="books"> -->
        
    <div class="form-div" >
        <form method="POST" action="add_new_book" class="form-inline">
            {% csrf_token %}
        <label style="font-size: 13px; margin-top:-70px;margin-bottom: -15; display:block;">Book Title</label><br><div>{{form.book_title}}</div>
        <label style="font-size: 13px;">Book Author</label><br> <div> {{form.book_author}}</div>
        <label style="font-size: 13px;">Number of pages</label><br> <div> {{form.book_pages}}</div>
        <label style="font-size: 13px;">Book's Category</label><br> <div> {{form.book_category}}</div>
        <label style="font-size: 13px;">Short summary of the book<i>(if any)</i></label><br> <div> {{form.book_description}}</div>
        <!-- <div>
            <label>Multiple Same Books</label>    
            <input type="radio" name="mode" id="multiple" value="Multiple" onclick="toggle_quantity_input(id)">
            <label>Single  book</label>    
            <input type="radio" value="single" name="mode" id="single" onclick="toggle_quantity_input(id)">

            <div id="additional_data">
                <b>Note:<i>For multiple copies, separate book number with a comma (',')</i> </b>
                <div id="multi">
                    <label>Enter the Book Quantity</label><br>
                    <input type="number" min="1" name="book_quantity"><br>
                </div>
                <label >Book Number(if any) </label><br>
                <input name="book_number_list">
            </div>
        </div> -->
        <br> <button style="font-size: 13px; margin-top:8px;"type="submit" class="btn btn-success">Add Book</button> 
        </form>
    </div>

    <!-- <div id="new_book_instance" class="books">
    <form method="POST" action="add_new_book_instance" class="form-inline">
        {% csrf_token %}
        <label>Book</label><br><div>{{form_instance.book}}</div>
        <label>Book Number</label>
        <div>{{form_instance.book_number}}</div>
        <br> <button type="submit" class="btn btn-success">Add Book</button> 
    </form>
    </div> -->

<script type="text/javascript">
    function opentab(tab_name){
         var tab=document.getElementById(tab_name);
         var i, tabcontent, tablinks;
         tabcontent = document.getElementsByClassName("books");
         for (i = 0; i < tabcontent.length; i++) {
             tabcontent[i].style.display = "none";
         }
         tablinks = document.getElementsByClassName("link");
         for (i = 0; i < tablinks.length; i++) {
             tablinks[i].className = tablinks[i].className.replace(" active", "");
         }
         tab.style.display = "block";

    }
    // function toggle_quantity_input(id){
    //     var obj=document.getElementById("multi");
    //     document.getElementById("additional_data").style.display="block";
    //     if(id=="single"){
    //         obj.style.display="none";
    //     }
    //     else{
    //         obj.style.display="block";   
    //     }
    // }
</script>
</div>
{% endblock %}
</body>

</html>

library/templates/add_new_student.html
<title>Add New Student</title>
{% extends 'base.html' %}

<body>
    
{% block content %}
<div class="form-div" >
<div class="form">
<form method="POST" action="add_new_student" style="
padding: 30px;" >
    {% csrf_token %}
    <label style="margin-bottom:5px; display:block; background-color: rgb(52, 2, 52); padding-top: 5px; padding-bottom: 5px;"  class="label-default">Student Details</label><br>
    <label style="font-size: 13px;">Matriculationn Number:</label><div style="margin-bottom:5px;">{{form.mat_no}}</div>
    <label style="font-size: 13px;">Student fullame:</label><div style="margin-bottom:5px;" > {{form.fullname}}</div>
    <label style="font-size: 13px;">Student Study Program:</label><div style="margin-bottom:5px;"> {{form.study_program}}</div>
    <label style="font-size: 13px;">Student department:</label><div style="margin-bottom:5px;">{{form.student_dept}}</div>
    <label style="font-size: 13px;">Student Faculty:</label><div style="margin-bottom:5px;">{{form.student_faculty}}</div>
    <label style="font-size: 13px;">Valid Email:</label><div style="margin-bottom:5px;">{{form.email}}</div>
    <br> <button style="margin-top: -9px;" type="submit" class="btn btn-success">Add Student</button>
</form>
</div>
</div>
{% endblock %}

</body>
</html>

library/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
{%load static%}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Alegreya Sans' rel='stylesheet'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: "Lato", sans-serif;
  margin-top: 0px;
  height: 100%;
}
tr {
  display: grid;
  grid-template-columns: 1fr 2fr 1fr 1fr 1fr 1fr 1fr 0.5fr;
  justify-items: center;
  border-style: solid;
  border-width: thin;
  border-left: 0px;
  border-right: 0px;
  border-top: 0px;
  border-color: white;
}

.table{
  margin-left:auto;
  margin-right:auto; 
  width: 100%;
}

tr .th{
  color:white; 
  padding:  5px 10px; 
  text-align: center; 
  font-weight:bold; 
  font-size:14px;
}

tr .td{
  color:white; 
  padding: 3px; 
  text-align: center; 
  font-weight:bold; 
  font-size:12px;
}
.bg {
  background-image: url('static/images/bg_mobile.jpeg');
  height: 100%; 
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

.big-container{
  position:relative;
  margin: 20px 0px; 
  width:100%; 
  height:80%; 
  overflow-x: scroll; 
  overflow-y: scroll; 
  background-color:rgb(3, 54, 105); 
  opacity:0.7 ;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  right: 0;
  background-color:red;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidenav a {
  text-decoration: none;
  color: #d2baba;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.sidenav .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 40px;
  color: white;
  margin:12px; 
  padding: 8px;
  padding: 8px;
  opacity: 0.6 
  /* border-radius:50%; 
  background-color: rgb(18, 3, 43); */
}

.dropdown-container {
  display: none;
  padding-left: 8px;
  margin:0px 0px 0px 32px;
  border-radius: 10px;
}

.active {
  color: white;
}

.heading {
  margin: 0px;
  padding: 20px 32px;
  font-size: 18px;
  font-family:'Alegreya Sans';
  border-color: white;
  border-style:groove ;
  border-width: thin;
  border-left: 0px;
  border-right: 0px;
}

.subheading{
  margin: 0px;
  padding: 10px 8px;
  font-size: 15px;
  font-family:'Alegreya Sans';
  border-color: white;
  border-style:groove ;
  border-width: thin;
  border-top: 0px;
  border-left: 0px;
  border-right: 0px;
  opacity: 0.7;
} 

.logo{
  font-size:22px;
  margin:0px 5px; 
  padding: 18px 10px ;
  color: white;
  font-weight: bold;
  background-color:red;
  font-family:'Sofia';
}
.opennav{
  font-size:30px;
  width: 40px; 
  text-align: center; 
  cursor:pointer; 
  right:0px; 
  position: fixed; 
  top:0px; 
  margin:12px; 
  padding: 8px; 
  border-radius:50%; 
  color: white;
}

.form-div{
  position:relative;
  margin: 20px 0px; 
  width:100%; 
  height:80%; 
  overflow-y: scroll; 
  border-radius: 10px;
  background-color:rgb(3, 54, 105); 
  opacity:0.7 ;
  text-align: center;
}
form{
  display: inline-block;
  padding: 100px;
  height: 60%;
  width: 50%;
}
label{
  color: white;
}
input{
  margin: 5px;
  border-radius: 7px;
  box-shadow: none;
  border-style: thin;
  width: 25%;
  height: 10%;

}
select{
  height: 10%;
  color: white;
  background-color: black;
  width: 50%;
  border-radius: 10px;
}
button{
  background-color: rgb(7, 7, 75); 
  margin-top: -6%; 
  font-size: 15px; 
  padding:8px; 
  border-radius: 14px; 
  color:white;
}

@media screen and (min-width: 400px) {
  .subheading{font-size: 19px;}
  .heading{font-size:24px ;}
  .logo{font-size: 30px;}
}

@media screen and (min-width: 500px) {
  .bg{background-image: url('static/images/bg_pc.jpeg'); height: 100%; background-position: center;background-repeat: no-repeat; background-size: cover; }
  .logo{font-size: 25px; padding: 12px 10px 12px 30px ;}
  .subheading{font-size: 14px;}
  .heading{font-size:17px ;}
  .opennav{margin-right:30px; margin-top:-0.5px ;}
  .big-container{overflow-x: hidden;}
}
</style>
</head>
<body>
<div class="bg">
<div class="logo">Eunice iLibrary</div>
<span class="opennav"  onclick="openNav()">&#9776; </span>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <nav class="nav">
    <a href="/" class="heading" style="border-top:0px;">Home</a>

    <a href="#" class="dropdown-btn">
        <p class="heading">Manage Students <i style="font-size:18px; " class="fa fa-caret-down"></i></p>
    </a>
    <span class="dropdown-container">
        <a href="./add_new_student" class="subheading">Create student profile</a>
        <a href="./show_students" class="subheading">All students</a>
    </span>
    <!-- <a href="#" class="dropdown-btn">
        <p class="heading">Manage Staffs <i style="font-size:18px; " class="fa fa-caret-down"></i></p>
    </a>
    <span class="dropdown-container">
        <a href="#" class="subheading">Create staff Profile</a>
        <a href="#" class="subheading">All Staffs</a>
    </span> -->
    
    <a href="./add_book_issue" class="heading" style="border-top:0px;">Charge Book</a>
    <a href="add_new_book" class="heading" style="border-top:0px;">Register Book</a>
    <a href="view_books" class="heading" style="border-top:0px;">All Books</a>
    <a href="view_books_issued" class="heading" style="border-top:0px;">Issued Books</a>

    <!-- <a href="#" class="heading">Sign Out</a> -->
</div>



<!-- Page content -->

{% block content %}
{% endblock %}

<!-- Page content -->

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "20%";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>



<script>
    /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;
    
    for (i = 0; i < dropdown.length; i++) {
      dropdown[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var dropdownContent = this.nextElementSibling;
        if (dropdownContent.style.display === "block") {
          dropdownContent.style.display = "none";
        } else {
          dropdownContent.style.display = "block";
        }
      });
    }
    </script>
</div>
</body>
</html> 

library/templates/edit_student_data.html
<title>Edit Student</title>
{% extends 'base.html' %}

<body>
{% block content %}

<div class="form">
<form method="POST" action=""  id="edit_student_data">
    {% csrf_token %}
    <label>Details</label>
    <label>Roll Number:</label><br>
    {{student}}
    <!-- <input type="text" name="roll_number" value={{student.roll_number}} required><br>
    <label>Student Name:</label><br>
    <input type="text" name="student_name" value={{student.fullname}} required><br>
    <label>Student Address:</label><br> 
    <input type="text" name="address" value={{student.address}} required><br>
    <label>Student Study Program:</label><br> 
    <input type="text" name="program" value={{student.program}} required><br>
    <label>Student Guardian/Parent Details</label><br>
    <label>Full name:</label><br> 
    <input type="text" name="Guardian_name" value={{student.Guardian_name}} required><br>
    <label>Valid Email:</label><br> 
    <input type="email" name="email" value="{{student.Email}}" required><br> -->
    <br> <button type="submit" class="btn btn-success">OK</button>
</form>
</div>
{% endblock %}
</body>

</html>

library/templates/index.html
<title>Library Management System</title>
{% extends 'base.html' %}

<body>
{% block content %}
{%load static%}

<div class="form-div" >
<img src="{%static 'images/Quotes/Quote-5.png' %}">
<!-- <input type="text" value="{{choosen_img}}"> -->


<style>
    img{
        height:80%;
        width:auto;
        margin-top: 3%;
        margin-bottom: 1%;
        border-radius:3em;
        display: inline-block;
    }
</style>
</div>
{% endblock %}
</body>
</html>

library/templates/issue_records.html
<title> Issue Records </title>
{% extends 'base.html' %}
<body>
{% block content %}
<div class="big-container" >
    <table class="table table-striped"> 
    <tr class="tr">
        <th class="th">Student name </th>
        <th class="th">Book ID </th>
        <th class="th">Issue Date </th>
        <th class="th">Due Date</th>
        <th class="th">Remarks on Issuing</th>
        <th class="th">Remarks on Return</th>
        <th class="th">Returned</th>
        <th class="th">Actions</th>
    </tr>
        {%for i in issue%}
        <tr class="tr">
            <td class="td">{{i.student}}</td>
            <td class="td">{{i.book_instance.id}}</td>
            <td class="td">{{i.issue_date}}</td>
            <td class="td">{{i.due_date}}</td>
            <td class="td">{{i.remarks_on_issue}}</td>
            <td class="td">{{i.remarks_on_return}}</td>
            <td class="td">
                {%if i.book_instance.Is_borrowed %}
                <span>No <i class="fa fa-times-circle" style="font-size:14px; color:rgb(249, 248, 248)"></i></span>
                <td class="td">
                    <a href="return_book/{{i.id}}"></i><i class="fa fa-book" style="color:rgb(249, 248, 248)"></i></a> |
                    <a href="edit_issued/{{i.id}}"><i class="fa fa-edit" style="color:rgb(249, 248, 248)"></i> </a>
                </td>
                {%else%}
                <span>Yes<i class="fa fa-check-circle" style="color:rgb(255, 255, 255); font-size:14px;"></i></span>
                <td class="td"><a href="edit_issued/{{i.id}}"><i class="fa fa-edit" style="color:rgb(249, 248, 248)"></i> </a> | <a href="delete_issued/{{i.id}}"><i class="fa fa-trash-alt" style="color:rgb(249, 248, 248)"></i></a></td>
                {%endif%}
            </td>
    
            
            
        </tr> {% endfor %}
    </table>
    
</div>
{% endblock %}
</body>
</html>